### PR TITLE
Remove error task, when it's a kill action - fix #76

### LINKED ISSUE #76: Remove kill node
As discussed with @mik-laj, we should implement a KillMapper, which will remove the error node only if it's of type `kill`.

Otherwise, for example if one action's error action is to execute another task, it should be left untouched.

### PR DESCRIPTION
**Pull request by mik-laj**
Hello,

I implement a fix for issues: #76 

I note that the base branch is a [workflow-tests](https://github.com/GoogleCloudPlatform/cloud-composer/pull/82).

Before DAG: 
image
Source code: https://gist.github.com/mik-laj/0a2b1d02dfe63195b705eac70faf42ad

After DAG:
image

Source code: 
https://gist.github.com/mik-laj/df47f1b76112bd127f8db80d89a61e3f

### CODE REVIEW

**Comment by potiuk** [comment]
Is it something we should take a look at @mik-laj  ?

**Comment by mik-laj** [comment]
Yes. It's working.

**Comment by sprzedwojski** [comment]
Let's not use `[WIP]` in the title. Let's use draft PRs as we agreed.

**Comment by sprzedwojski** [comment]
Ok, but in this case I'd still use a draft PR rather than `[WIP]`.

**Comment by sprzedwojski** [comment]
Also in the PR title if you use e.g. "Closes #76" it will close the issue automatically once this PR is merged.
https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by mik-laj** [comment]
@sprzedwojski thanks. I updated a title of PR..

**Pull request merged**
